from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from .utility_functions import *
import requests
import pesapal
from .payment import postDirectOrder, queryPaymentDetails


def index(request):
    context = {
        'hero_text': 'Welcome to',
        'key_text': 'Cheka Business',
        'summary': 'We offer you access to classes, entertainment, business opportunity',
        'thumbnail': '/img/hero-img.png',
        'title': 'Cheka group'
    }
    return render(request, 'src/index.html', context)


def projects(request):
    categories = fetch_categories()
    all_projects = fetch_projects()

    context = {
        'categories': categories,
        'projects': all_projects,
        'hero_text': 'Build Your English language Skills With',
        'key_text': 'Cheka TV',
        'summary': 'We offer you one to one lessons with the Cheka TV staff',
        'thumbnail': '/img/hero-img.png',
        'title': 'Cheka projects'
    }
    return render(request, 'src/projects.html', context)

def project_detail(request, project_id):
    categories = fetch_categories()
    project = fetch_single_project(project_id)
    context = {
        'categories': categories,
        'project': project,
        'key_text': project.name,
        'summary': f'${project.price}',
        'checkout_amount': int(project.price * 100),
        'thumbnail': project.thumbnail,
        'title': project.name
    }

    return render(request, 'src/detail.html', context)


def project_checkout(request, project_id):
    project = fetch_single_project(project_id)
    request_data = {
        'Amount': str(int(project.price)),
        'Currency': 'USD',
        'Description': project.name,
        'Type': 'MERCHANT',
        'Reference': project.ref_id,
        'FirstName': request.POST.get('first_name'),
        'LastName': request.POST.get('last_name'),
        'Email': request.POST.get('email'),
    }
    post_params = {
        'oauth_callback': f'http://localhost:8000/project/payment'
    }
    # build url to redirect user to confirm payment
    url = postDirectOrder(post_params, request_data)
    context = {
        'url': url,
        'title': 'Checkout'
    }
    return render(request, 'src/checkout.html', context)


def pesapal_callback(request):
    ref_id = request.get('pesapal_merchant_reference')
    transaction_id = request.get('pesapal_transaction_tracking_id')
    project = Project.objects.filter(ref_id=ref_id).first()
    if project:
        Transaction.objects.create(
            transaction_id=transaction_id,
            project=project,
            payment_mode='CARD',
        )

    context = {
        'title': 'Check Payment',
        'transaction_id': transaction_id,
        'show_success': False,
    }
    return render(request, 'src/check_transaction.html', context)


def query_payment_status(request):
    transaction_id = request.POST.get('transaction_id')
    transaction = Transaction.objects.filter(transaction_id=transaction_id).first()
    params = {
        'pesapal_merchant_reference': transaction.project.ref_id,
        'pesapal_transaction_tracking_id': transaction_id
    }

    status = queryPaymentDetails(params)
    if status.split(',')[2] == 'COMPLETED':
        transaction.is_successful = True
        transaction.save()
        return render(request, 'src/success.html')
    elif status.split(',')[2] == 'PENDING':
        context = {
            'title': 'Check Payment',
            'transaction_id': '1212',
            'show_success': False,
        }
        return render(request, 'src/check_transaction.html', context)
    elif status.split(',')[2] == 'FAILED':
        transaction.is_successful = False
        transaction.save()
        return render(request, 'src/failure.html')
    else:  # INVALID
        transaction.is_successful = False
        transaction.save()
        return render(request, 'src/failure.html')


def check_transaction_pesapal(request, transaction_id):
    # get order status
    post_params = {
        'pesapal_merchant_reference': transaction_id,  # order_id
        'pesapal_transaction_tracking_id': transaction_id  # generated by pesapal
    }
    url = queryPaymentDetails(post_params)
    response = requests.get(url)
    print(response.json())


""" PesaPal Integration """
def pesapal_ipn():
    return 'IPN recieved'


""" Jenga API integration """
def payment_successful(request, project_id):
    project = Project.objects.filter(pk=project_id)
    if project:
        Transaction.objects.create(
            transaction_id=request.JSON.get('transactionId'),
            project=project,
            transaction_date=request.JSON.get('date'),
            amount=request.JSON.get('amount'),
            extra_data=request.JSON.get('extraData'),
            payment_mode=request.JSON.get('desc'),
            is_successful=True if request.JSON.get('status') == 'paid' else False
        )
        context = {
            'key_text': project.name,
            'project': project,
            'is_successful': True if request.JSON.get('status') == 'paid' else False
        }
        return render(request, 'src/success.html', context)
    else:
        messages.error(request, "Could not find the project!")
        context = {
            'key_text': "Error",
            'is_successful': False
        }
        return render(request, 'src/failure.html', context)


""" Jenga API integration """
def generate_token():
    url = "https://api-test.equitybankgroup.com/v1/token"

    payload = f"grant_type=password&merchantCode={settings.JENGA_USERNAME}&password={settings.JENGA_PASSWORD}"
    headers = {
        'authorization': settings.JENGA_API_KEY,
        'content-type': "application/x-www-form-urlencoded"
    }

    response = requests.request("POST", url, data=payload, headers=headers)
    print(response.json())

    return response.json()['payment-token'] if response.status_code == 200 else ''
