# Generated by Django 3.0.4 on 2020-04-22 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('57c94766-102e-4d21-924d-a76b1559cccb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('df4638e2-b050-46cb-b365-b15847f134f7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default=uuid.UUID('7b58a53b-7b68-4d5e-8899-79baaa2e9e39'), editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1e4c80b-2fe9-43a4-934b-ee621bb41831'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=uuid.UUID('853e9155-7b23-4b6f-a6e2-2e2c968ceaa5'), editable=False, max_length=10),
        ),
    ]
