# Generated by Django 3.0.4 on 2020-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20200509_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='5f6a7fc8', editable=False, max_length=8),
        ),
    ]
