# Generated by Django 3.0.4 on 2020-05-09 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200509_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationupdate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='e4af81d5', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='DonationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='The project comment will still be visible to public.', verbose_name='active')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Donation')),
            ],
            options={
                'verbose_name': 'Donation Comments',
                'verbose_name_plural': 'Donation Comments',
                'ordering': ['added_on'],
            },
        ),
    ]
