# Generated by Django 3.0.4 on 2020-05-09 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0010_auto_20200509_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='3d478ae4', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='DonationIncentives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Incentives',
                'verbose_name_plural': 'Donation Incentives',
                'ordering': ['-created_at'],
            },
        ),
    ]
