# Generated by Django 3.0.4 on 2020-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20200510_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ref_id',
            field=models.CharField(default='b1535f56', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='7dde7b0f', editable=False, max_length=8),
        ),
    ]
