# Generated by Django 3.0.4 on 2020-05-24 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20200523_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.IntegerField(choices=[(1, 'MORNING'), (2, 'AFTERNOON'), (3, 'EVENING'), (4, 'FREE TIME')], default=1)),
                ('time_start', models.DateTimeField()),
                ('duration', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ref_id',
            field=models.CharField(default='22bbc137', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='d1e5a755', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='ProjectSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Schedule')),
            ],
        ),
    ]
