# Generated by Django 3.0.4 on 2020-05-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20200525_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ref_id',
            field=models.CharField(default='52aa52ae', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='889b034e', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
