# Generated by Django 3.0.4 on 2020-05-24 22:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20200525_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ref_id',
            field=models.CharField(default='c3411291', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='365ea2e9', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='ProjectDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY'), (0, 'SUNDAY')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('full_name', models.CharField(max_length=254, null=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Project')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ProjectSchedule')),
            ],
        ),
    ]
