# Generated by Django 3.0.4 on 2020-05-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20200525_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbookings',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='ref_id',
            field=models.CharField(default='253b7790', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='f394fca4', editable=False, max_length=8),
        ),
    ]
