# Generated by Django 3.0.4 on 2020-05-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20200525_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbookings',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(default='845fac30-bf8e-4514-b560-740b43a71afa', on_delete=django.db.models.deletion.CASCADE, to='application.ProjectBookings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='ref_id',
            field=models.CharField(default='b147aa5f', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='ref_id',
            field=models.CharField(default='727c49b8', editable=False, max_length=8),
        ),
    ]
