# Generated by Django 3.0.4 on 2020-04-29 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(default='default.png', upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='The category will be available.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='The item will be available.', verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone_address', models.CharField(max_length=20)),
                ('buyer_address', models.TextField()),
                ('discounted', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStages',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'processing_stages',
                'verbose_name_plural': 'processing_stages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True, help_text='The project will still be available.', verbose_name='active')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('seed_money', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'projects',
                'verbose_name_plural': 'projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(null=True, upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True, help_text='The project update will still be available.', verbose_name='active')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Project')),
            ],
            options={
                'verbose_name': 'project_updates',
                'verbose_name_plural': 'project_updates',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSeed',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Project')),
            ],
            options={
                'verbose_name': 'project_seeds',
                'verbose_name_plural': 'project_seeds',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(null=True, upload_to='uploads/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Project')),
            ],
            options={
                'verbose_name': 'project_images',
                'verbose_name_plural': 'project_images',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='The project comment will still be visible to public.', verbose_name='active')),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Project')),
            ],
            options={
                'verbose_name': 'project_comments',
                'verbose_name_plural': 'project_comments',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_done', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Order')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.ProcessingStages')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True, help_text='The image will be available.', verbose_name='active')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ecsite.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Item')),
            ],
        ),
    ]
