# Generated by Django 3.0.4 on 2020-04-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='default.png', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.FileField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='projects'),
        ),
    ]
