# Generated by Django 3.0.4 on 2020-05-01 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0002_auto_20200429_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_phone_address',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('public_id', models.UUIDField(default=uuid.UUID('636069af-33db-496b-b7a1-8004f5f0a82b'), editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecsite.Order')),
            ],
        ),
    ]
