# Generated by Django 3.0.4 on 2020-05-01 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0003_auto_20200501_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('17d5a3b0-10e0-4dec-a32b-323b2f8918bf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
