# Generated by Django 3.0.4 on 2020-05-02 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0005_auto_20200502_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('aa1aa34c-3694-4149-907b-ff1ca171e08d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
