# Generated by Django 3.0.4 on 2020-05-23 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0007_auto_20200510_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('3cbbf9f2-1a8c-4ce8-a5b6-f57f5e2993a7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
