# Generated by Django 3.0.4 on 2020-05-24 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0008_auto_20200523_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('bdced298-be10-47bf-8930-06c8003a51c2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
