# Generated by Django 3.0.4 on 2020-05-24 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0010_auto_20200525_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('b443ed52-f3ec-4f10-ab70-a56f29eabb92'), editable=False, primary_key=True, serialize=False),
        ),
    ]
