# Generated by Django 3.0.4 on 2020-05-24 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0011_auto_20200525_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('80aa974c-2639-4545-9866-c014758c1f2b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
