# Generated by Django 3.0.4 on 2020-05-24 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0012_auto_20200525_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('a922f495-d813-4521-9805-8c692d58ed57'), editable=False, primary_key=True, serialize=False),
        ),
    ]
