# Generated by Django 3.0.4 on 2020-05-24 23:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0013_auto_20200525_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='public_id',
            field=models.UUIDField(default=uuid.UUID('dd9e798b-e515-44bf-921d-c2ef195084ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
